package com.ahmadpour.formapp.data.db.models;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ANSWERS".
 */
@Entity
public class Answers {

    @Id
    private Long id;
    private Long questionId;
    private Long optionId;
    private String answer;

    @Generated
    public Answers() {
    }

    public Answers(Long id) {
        this.id = id;
    }

    @Generated
    public Answers(Long id, Long questionId, Long optionId, String answer) {
        this.id = id;
        this.questionId = questionId;
        this.optionId = optionId;
        this.answer = answer;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getQuestionId() {
        return questionId;
    }

    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    public Long getOptionId() {
        return optionId;
    }

    public void setOptionId(Long optionId) {
        this.optionId = optionId;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

}
