package com.ahmadpour.formapp.data.db.models;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ANSWERS".
*/
public class AnswersDao extends AbstractDao<Answers, Long> {

    public static final String TABLENAME = "ANSWERS";

    /**
     * Properties of entity Answers.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property FormId = new Property(1, Long.class, "formId", false, "FORMID");
        public final static Property QuestionId = new Property(2, Long.class, "questionId", false, "QUESTIONID");
        public final static Property OptionId = new Property(3, Long.class, "optionId", false, "OPTIONID");
        public final static Property Answer = new Property(4, String.class, "answer", false, "ANSWER");
        public final static Property Temp = new Property(5, Integer.class, "temp", false, "TEMP");
        public final static Property Date = new Property(6, String.class, "date", false, "DATE");
    }


    public AnswersDao(DaoConfig config) {
        super(config);
    }
    
    public AnswersDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ANSWERS\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"FORM_ID\" INTEGER," + // 1: formId
                "\"QUESTION_ID\" INTEGER," + // 2: questionId
                "\"OPTION_ID\" INTEGER," + // 3: optionId
                "\"ANSWER\" TEXT," + // 4: answer
                "\"TEMP\" INTEGER," + // 5: temp
                "\"DATE\" TEXT);"); // 6: date
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ANSWERS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Answers entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long formId = entity.getFormId();
        if (formId != null) {
            stmt.bindLong(2, formId);
        }
 
        Long questionId = entity.getQuestionId();
        if (questionId != null) {
            stmt.bindLong(3, questionId);
        }
 
        Long optionId = entity.getOptionId();
        if (optionId != null) {
            stmt.bindLong(4, optionId);
        }
 
        String answer = entity.getAnswer();
        if (answer != null) {
            stmt.bindString(5, answer);
        }
 
        Integer temp = entity.getTemp();
        if (temp != null) {
            stmt.bindLong(6, temp);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(7, date);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Answers entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long formId = entity.getFormId();
        if (formId != null) {
            stmt.bindLong(2, formId);
        }
 
        Long questionId = entity.getQuestionId();
        if (questionId != null) {
            stmt.bindLong(3, questionId);
        }
 
        Long optionId = entity.getOptionId();
        if (optionId != null) {
            stmt.bindLong(4, optionId);
        }
 
        String answer = entity.getAnswer();
        if (answer != null) {
            stmt.bindString(5, answer);
        }
 
        Integer temp = entity.getTemp();
        if (temp != null) {
            stmt.bindLong(6, temp);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(7, date);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Answers readEntity(Cursor cursor, int offset) {
        Answers entity = new Answers( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // formId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // questionId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // optionId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // answer
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // temp
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // date
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Answers entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFormId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setQuestionId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setOptionId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setAnswer(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTemp(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setDate(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Answers entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Answers entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Answers entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
