package com.ahmadpour.formapp.data.db.models;

import android.os.Parcel;
import android.os.Parcelable;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ANSWERS".
 */
@Entity
public class Answers implements Parcelable{

    @Id
    private Long id;
    private Long formId;
    private Long questionId;
    private Long optionId;
    private String answer;
    private Questions question;

    @Generated
    public Answers() {
    }

    public Answers(Long id) {
        this.id = id;
    }

    @Generated
    public Answers(Long id, Long formId, Long questionId, Long optionId, String answer) {
        this.id = id;
        this.formId = formId;
        this.questionId = questionId;
        this.optionId = optionId;
        this.answer = answer;
    }

    protected Answers(Parcel in) {
        if (in.readByte() == 0) {
            id = null;
        } else {
            id = in.readLong();
        }
        if (in.readByte() == 0) {
            formId = null;
        } else {
            formId = in.readLong();
        }
        if (in.readByte() == 0) {
            questionId = null;
        } else {
            questionId = in.readLong();
        }
        if (in.readByte() == 0) {
            optionId = null;
        } else {
            optionId = in.readLong();
        }
        answer = in.readString();
        question = in.readParcelable(Questions.class.getClassLoader());
    }

    public static final Creator<Answers> CREATOR = new Creator<Answers>() {
        @Override
        public Answers createFromParcel(Parcel in) {
            return new Answers(in);
        }

        @Override
        public Answers[] newArray(int size) {
            return new Answers[size];
        }
    };

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFormId() {
        return formId;
    }

    public void setFormId(Long formId) {
        this.formId = formId;
    }

    public Long getQuestionId() {
        return questionId;
    }

    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    public Long getOptionId() {
        return optionId;
    }

    public void setOptionId(Long optionId) {
        this.optionId = optionId;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public Questions getQuestion() {
        return question;
    }

    public void setQuestion(Questions question) {
        this.question = question;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel parcel, int i) {
        if (id == null) {
            parcel.writeByte((byte) 0);
        } else {
            parcel.writeByte((byte) 1);
            parcel.writeLong(id);
        }
        if (formId == null) {
            parcel.writeByte((byte) 0);
        } else {
            parcel.writeByte((byte) 1);
            parcel.writeLong(formId);
        }
        if (questionId == null) {
            parcel.writeByte((byte) 0);
        } else {
            parcel.writeByte((byte) 1);
            parcel.writeLong(questionId);
        }
        if (optionId == null) {
            parcel.writeByte((byte) 0);
        } else {
            parcel.writeByte((byte) 1);
            parcel.writeLong(optionId);
        }
        parcel.writeString(answer);
        parcel.writeParcelable(question, i);
    }
}
