package com.ahmadpour.formapp.data.db.models;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ahmadpour.formapp.data.db.models.Forms;
import com.ahmadpour.formapp.data.db.models.Questions;
import com.ahmadpour.formapp.data.db.models.Options;
import com.ahmadpour.formapp.data.db.models.Answers;

import com.ahmadpour.formapp.data.db.models.FormsDao;
import com.ahmadpour.formapp.data.db.models.QuestionsDao;
import com.ahmadpour.formapp.data.db.models.OptionsDao;
import com.ahmadpour.formapp.data.db.models.AnswersDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig formsDaoConfig;
    private final DaoConfig questionsDaoConfig;
    private final DaoConfig optionsDaoConfig;
    private final DaoConfig answersDaoConfig;

    private final FormsDao formsDao;
    private final QuestionsDao questionsDao;
    private final OptionsDao optionsDao;
    private final AnswersDao answersDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        formsDaoConfig = daoConfigMap.get(FormsDao.class).clone();
        formsDaoConfig.initIdentityScope(type);

        questionsDaoConfig = daoConfigMap.get(QuestionsDao.class).clone();
        questionsDaoConfig.initIdentityScope(type);

        optionsDaoConfig = daoConfigMap.get(OptionsDao.class).clone();
        optionsDaoConfig.initIdentityScope(type);

        answersDaoConfig = daoConfigMap.get(AnswersDao.class).clone();
        answersDaoConfig.initIdentityScope(type);

        formsDao = new FormsDao(formsDaoConfig, this);
        questionsDao = new QuestionsDao(questionsDaoConfig, this);
        optionsDao = new OptionsDao(optionsDaoConfig, this);
        answersDao = new AnswersDao(answersDaoConfig, this);

        registerDao(Forms.class, formsDao);
        registerDao(Questions.class, questionsDao);
        registerDao(Options.class, optionsDao);
        registerDao(Answers.class, answersDao);
    }
    
    public void clear() {
        formsDaoConfig.clearIdentityScope();
        questionsDaoConfig.clearIdentityScope();
        optionsDaoConfig.clearIdentityScope();
        answersDaoConfig.clearIdentityScope();
    }

    public FormsDao getFormsDao() {
        return formsDao;
    }

    public QuestionsDao getQuestionsDao() {
        return questionsDao;
    }

    public OptionsDao getOptionsDao() {
        return optionsDao;
    }

    public AnswersDao getAnswersDao() {
        return answersDao;
    }

}
