package com.ahmadpour.formapp.data.db.models;

import android.os.Parcel;
import android.os.Parcelable;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "OPTIONS".
 */
@Entity
public class Options implements Parcelable{

    @Id
    private Long id;
    private Long formId;
    private Long questionId;
    private String option;

    @Generated
    public Options() {
    }

    public Options(Long id) {
        this.id = id;
    }

    @Generated
    public Options(Long id, Long formId, Long questionId, String option) {
        this.id = id;
        this.formId = formId;
        this.questionId = questionId;
        this.option = option;
    }

    protected Options(Parcel in) {
        if (in.readByte() == 0) {
            id = null;
        } else {
            id = in.readLong();
        }
        if (in.readByte() == 0) {
            formId = null;
        } else {
            formId = in.readLong();
        }
        if (in.readByte() == 0) {
            questionId = null;
        } else {
            questionId = in.readLong();
        }
        option = in.readString();
    }

    public static final Creator<Options> CREATOR = new Creator<Options>() {
        @Override
        public Options createFromParcel(Parcel in) {
            return new Options(in);
        }

        @Override
        public Options[] newArray(int size) {
            return new Options[size];
        }
    };

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFormId() {
        return formId;
    }

    public void setFormId(Long formId) {
        this.formId = formId;
    }

    public Long getQuestionId() {
        return questionId;
    }

    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    public String getOption() {
        return option;
    }

    public void setOption(String option) {
        this.option = option;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel parcel, int i) {
        if (id == null) {
            parcel.writeByte((byte) 0);
        } else {
            parcel.writeByte((byte) 1);
            parcel.writeLong(id);
        }
        if (formId == null) {
            parcel.writeByte((byte) 0);
        } else {
            parcel.writeByte((byte) 1);
            parcel.writeLong(formId);
        }
        if (questionId == null) {
            parcel.writeByte((byte) 0);
        } else {
            parcel.writeByte((byte) 1);
            parcel.writeLong(questionId);
        }
        parcel.writeString(option);
    }
}
