package com.ahmadpour.formapp.data.db.models;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "OPTIONS".
*/
public class OptionsDao extends AbstractDao<Options, Long> {

    public static final String TABLENAME = "OPTIONS";

    /**
     * Properties of entity Options.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property QuestionId = new Property(1, Long.class, "questionId", false, "QUESTION_ID");
        public final static Property Option = new Property(2, String.class, "option", false, "OPTION");
        public final static Property IsAnswer = new Property(3, Boolean.class, "isAnswer", false, "IS_ANSWER");
    }


    public OptionsDao(DaoConfig config) {
        super(config);
    }
    
    public OptionsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"OPTIONS\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"QUESTION_ID\" INTEGER," + // 1: questionId
                "\"OPTION\" TEXT," + // 2: option
                "\"IS_ANSWER\" INTEGER);"); // 3: isAnswer
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"OPTIONS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Options entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long questionId = entity.getQuestionId();
        if (questionId != null) {
            stmt.bindLong(2, questionId);
        }
 
        String option = entity.getOption();
        if (option != null) {
            stmt.bindString(3, option);
        }
 
        Boolean isAnswer = entity.getIsAnswer();
        if (isAnswer != null) {
            stmt.bindLong(4, isAnswer ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Options entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long questionId = entity.getQuestionId();
        if (questionId != null) {
            stmt.bindLong(2, questionId);
        }
 
        String option = entity.getOption();
        if (option != null) {
            stmt.bindString(3, option);
        }
 
        Boolean isAnswer = entity.getIsAnswer();
        if (isAnswer != null) {
            stmt.bindLong(4, isAnswer ? 1L: 0L);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Options readEntity(Cursor cursor, int offset) {
        Options entity = new Options( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // questionId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // option
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // isAnswer
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Options entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQuestionId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setOption(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsAnswer(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Options entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Options entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Options entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
