package com.ahmadpour.formapp.data.db.models;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "OPTIONS".
*/
public class OptionsDao extends AbstractDao<Options, Long> {

    public static final String TABLENAME = "OPTIONS";

    /**
     * Properties of entity Options.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property FormId = new Property(1, Long.class, "formId", false, "FORMID");
        public final static Property QuestionId = new Property(2, Long.class, "questionId", false, "QUESTIONID");
        public final static Property Option = new Property(3, String.class, "option", false, "OPTION");
    }


    public OptionsDao(DaoConfig config) {
        super(config);
    }
    
    public OptionsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"OPTIONS\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"FORM_ID\" INTEGER," + // 1: formId
                "\"QUESTION_ID\" INTEGER," + // 2: questionId
                "\"OPTION\" TEXT);"); // 3: option
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"OPTIONS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Options entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long formId = entity.getFormId();
        if (formId != null) {
            stmt.bindLong(2, formId);
        }
 
        Long questionId = entity.getQuestionId();
        if (questionId != null) {
            stmt.bindLong(3, questionId);
        }
 
        String option = entity.getOption();
        if (option != null) {
            stmt.bindString(4, option);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Options entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long formId = entity.getFormId();
        if (formId != null) {
            stmt.bindLong(2, formId);
        }
 
        Long questionId = entity.getQuestionId();
        if (questionId != null) {
            stmt.bindLong(3, questionId);
        }
 
        String option = entity.getOption();
        if (option != null) {
            stmt.bindString(4, option);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Options readEntity(Cursor cursor, int offset) {
        Options entity = new Options( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // formId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // questionId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // option
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Options entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFormId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setQuestionId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setOption(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Options entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Options entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Options entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
