package com.ahmadpour.formapp.data.db.models;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "QUESTIONS".
 */
@Entity
public class Questions {

    @Id
    private Long id;
    private Long formId;
    private String question;
    private Integer type;

    @Generated
    public Questions() {
    }

    public Questions(Long id) {
        this.id = id;
    }

    @Generated
    public Questions(Long id, Long formId, String question, Integer type) {
        this.id = id;
        this.formId = formId;
        this.question = question;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFormId() {
        return formId;
    }

    public void setFormId(Long formId) {
        this.formId = formId;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
